### PR TITLE
Add stochastic volatility model

### PR DESCRIPTION
**Pull request by wazizian**
Hi !
First, thank your work on these SMC packages, they look great :-)
To get familiar with your SMC implementation, I tested it on a simple stochastic volatility model, with a simple approximation of the optimal proposal (taken from the book by Nicolas Chopin and Omiros Papaspiliopoulos).
If you think this might interest others and you are willing to consider merging it, I'd be happy to take into account your feedback :-)
(and, in any case, I'm happy to get any feedback, since I plan to use to SMC.jl in a project).
Cheers,
Waïss

### CODE REVIEW

**Comment by awllee** [comment]
Looks like

1. your tests are failing on 1.0;
2. there is an issue with SequentialMonteCarlo.jl in Julia 1.7.

I will try to fix 2. I think I know what the issue is.

**Comment by wazizian** [comment]
Sorry, my bad, I tested only with one seed and it turns out there is a lot of variance, so I removed them...
(The proposal distribution I used is supposed to approximately minimize the variance of certain quantities but it is not straightforward to test).

**Comment by awllee** [comment]
No problem. I'm waiting for SequentialMonteCarlo.jl to be updated in the registry before re-running checks.

On the other hand, it seems to me that your G function is not correct, since you define the same G irrespective of whether M is guided or not. See, e.g., Algorithm 10.5 of your reference C & P.

Please let me know if I've misunderstood what you are doing. Also, perhaps it would make sense to have a test that checks whether some estimates are close for the guided and unguided models, for some large N? Just to make sure that indeed they are approximating the same quantities.

And thanks for the PR, I am of course happy for you to contribute!

**Comment by awllee** [comment]
Looks like the code runs now without any problems. When you respond to / address the concern in my last message I will be happy to merge.

**Comment by wazizian** [comment]
Thanks a lot for your feedback, the G function was indeed incorrect.
I fixed this and added a few tests to check that the estimated filtering and predictive means are indeed similar.

**Comment by awllee** [comment]
Great, thanks!

**Pull request merged**
